language: python
sudo: required
services: docker

matrix:
  include:
    - env: CONTAINER_IMAGE=py36 TOXENV=py36

install:
  - pip install coveralls
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - sed -i -e s@/build@"$(pwd)"@g .coverage
  - coveralls
